"""A structural CodeExecutor implementation with explicit process ownership."""
from __future__ import annotations
import asyncio
import os
import shlex
import uuid
from types import MappingProxyType

from openagent_shell.shell_core import BackgroundShell
from .backends import DockerBackend


class _Process(BackgroundShell):
    def __init__(self, *, backend, bridge_transport, **kwargs):
        super().__init__(base_environment={}, **kwargs)
        self.backend, self.bridge_transport = backend, bridge_transport
        self.remote_pidfile = f"/tmp/oa-code-{self.shell_id}.pid"

    async def _spawn_process(self):
        command = self.command
        if isinstance(self.backend, DockerBackend):
            # One remote process group per call. Killing only docker-exec would
            # otherwise leave code running in the provisioned environment.
            command = ("command -v setsid >/dev/null || exit 127; "
                f"setsid bash -c {shlex.quote(command)} & p=$!; "
                f"echo $p > {shlex.quote(self.remote_pidfile)}; wait $p; r=$?; "
                f"rm -f {shlex.quote(self.remote_pidfile)}; exit $r")
        spec = self.backend.build_spawn(command=command, cwd=self.cwd, env=dict(self.env))
        common = dict(stdin=asyncio.subprocess.PIPE, stdout=asyncio.subprocess.PIPE,
                      stderr=asyncio.subprocess.PIPE, cwd=spec.cwd,
                      env=dict(self.env) if self.bridge_transport == "unix" else spec.env)
        if os.name == "nt" and self.bridge_transport == "unix":
            return await asyncio.create_subprocess_shell(self.command, **common)
        # Every host-side client has its own process group too. This avoids
        # forwarding a cancellation signal into the gateway's process group.
        return await asyncio.create_subprocess_exec(*spec.argv, start_new_session=True, **common)

    async def kill(self, *, signal_name="TERM", grace_seconds=5.0):
        if isinstance(self.backend, DockerBackend):
            try:
                # The pidfile path is generated by this executor and is never
                # accepted from model arguments or a completion event.
                command = (f"if test -f {shlex.quote(self.remote_pidfile)}; then "
                    f"p=$(cat {shlex.quote(self.remote_pidfile)}); "
                    "case $p in ''|*[!0-9]*) exit 2;; esac; "
                    f"kill -{signal_name} -- -$p 2>/dev/null || true; fi")
                await asyncio.wait_for(self.backend._exec(["bash", "-c", command]), 5)
            finally:
                await super().kill(signal_name=signal_name, grace_seconds=grace_seconds)
            if signal_name != "KILL":
                await self.kill(signal_name="KILL", grace_seconds=0)
        else:
            await super().kill(signal_name=signal_name, grace_seconds=grace_seconds)


class ProcessCodeExecutor:
    """The host must choose every execution and isolation option explicitly.

    Construction does not spawn processes. ``close`` only closes this instance's
    backend and active commands. No engine imports or process-wide registries.
    """
    def __init__(self, *, backend, python_executable: str, bridge_transport: str,
                 isolated: bool, environment, workdir: str = ""):
        if bridge_transport not in {"unix", "files"} or not python_executable:
            raise ValueError("An explicit executor transport and Python executable are required")
        if bridge_transport == "files" and not all(callable(getattr(backend, f"container_{name}", None))
                for name in ("mkdir", "listdir", "read", "write", "rmtree")):
            raise ValueError("The selected backend cannot provide a filesystem RPC bridge")
        if bridge_transport == "unix" and getattr(backend, "name", None) != "local":
            raise ValueError("Remote execution requires an explicit filesystem RPC bridge")
        if bridge_transport == "files" and not workdir:
            raise ValueError("A remote executor requires an explicit workdir")
        self.backend = backend
        self.python_executable, self.bridge_transport = python_executable, bridge_transport
        self.isolated, self.workdir = bool(isolated), workdir
        self.environment = MappingProxyType(dict(environment))
        self._active = set()
        self._prepare_lock = asyncio.Lock()
        self._closed = False

    async def prepare(self, context):
        async with self._prepare_lock:
            if self._closed:
                raise RuntimeError("The code executor is closed")
            await self.backend.prepare()

    async def run(self, *, command, cwd, env, timeout_seconds, context):
        await self.prepare(context)
        process = _Process(backend=self.backend, bridge_transport=self.bridge_transport,
            shell_id=uuid.uuid4().hex, command=command, cwd=cwd, env=dict(env))
        self._active.add(process)
        try:
            return await process.run_with_timeout(timeout_seconds=timeout_seconds)
        finally:
            self._active.discard(process)

    async def close(self):
        async with self._prepare_lock:
            self._closed = True
            await asyncio.gather(*(p.kill(signal_name="KILL", grace_seconds=0)
                for p in tuple(self._active)), return_exceptions=True)
            await self.backend.cleanup()

    async def files_mkdir(self, path): return await self.backend.container_mkdir(path)
    async def files_listdir(self, path): return await self.backend.container_listdir(path)
    async def files_read(self, path): return await self.backend.container_read(path)
    async def files_write(self, path, data): return await self.backend.container_write(path, data)
    async def files_rmtree(self, path): return await self.backend.container_rmtree(path)
